#############################################################################
# Makefile for building: NuMeth
# Generated by qmake (2.01a) (Qt 4.3.3) on: Fri Feb 5 16:25:31 2010
# Project:  NuMeth.pro
# Template: app
# Command: /remote/apps/depot/linux/Qt-4.3.3/bin/qmake -unix -o Makefile NuMeth.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../apps/depot/linux/Qt-4.3.3/mkspecs/linux-g++ -I. -I../../../apps/depot/linux/Qt-4.3.3/include/QtCore -I../../../apps/depot/linux/Qt-4.3.3/include/QtCore -I../../../apps/depot/linux/Qt-4.3.3/include/QtGui -I../../../apps/depot/linux/Qt-4.3.3/include/QtGui -I../../../apps/depot/linux/Qt-4.3.3/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/remote/apps/depot/linux/Qt-4.3.3/lib
LIBS          = $(SUBLIBS)  -L/remote/apps/depot/linux/Qt-4.3.3/lib -lQtGui -lQtCore -lz -lm -pthread -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /remote/apps/depot/linux/Qt-4.3.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = derivation.cpp \
		divideddiffs.cpp \
		function.cpp \
		functionparser.cpp \
		integration.cpp \
		interpolation.cpp \
		main.cpp \
		mainwindow.cpp \
		numethwizard.cpp \
		plotter.cpp moc_mainwindow.cpp \
		moc_numethwizard.cpp \
		moc_plotter.cpp \
		qrc_numeth.cpp \
		qrc_numethwizard.cpp \
		qrc_plotter.cpp
OBJECTS       = derivation.o \
		divideddiffs.o \
		function.o \
		functionparser.o \
		integration.o \
		interpolation.o \
		main.o \
		mainwindow.o \
		numethwizard.o \
		plotter.o \
		moc_mainwindow.o \
		moc_numethwizard.o \
		moc_plotter.o \
		qrc_numeth.o \
		qrc_numethwizard.o \
		qrc_plotter.o
DIST          = ../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/g++.conf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/unix.conf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/linux.conf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/qconfig.pri \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt_functions.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt_config.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/exclusive_builds.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/default_pre.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/release.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/default_post.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/warn_on.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/unix/thread.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/moc.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/resources.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/uic.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/yacc.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/lex.prf \
		NuMeth.pro
QMAKE_TARGET  = NuMeth
DESTDIR       = 
TARGET        = NuMeth

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NuMeth.pro  ../../../apps/depot/linux/Qt-4.3.3/mkspecs/linux-g++/qmake.conf ../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/g++.conf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/unix.conf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/linux.conf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/qconfig.pri \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt_functions.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt_config.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/exclusive_builds.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/default_pre.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/release.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/default_post.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/warn_on.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/unix/thread.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/moc.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/resources.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/uic.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/yacc.prf \
		../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/lex.prf \
		/remote/apps/depot/linux/Qt-4.3.3/lib/libQtGui.prl \
		/remote/apps/depot/linux/Qt-4.3.3/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile NuMeth.pro
../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/g++.conf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/unix.conf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/common/linux.conf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/qconfig.pri:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt_functions.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt_config.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/exclusive_builds.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/default_pre.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/release.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/default_post.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/warn_on.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/qt.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/unix/thread.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/moc.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/resources.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/uic.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/yacc.prf:
../../../apps/depot/linux/Qt-4.3.3/mkspecs/features/lex.prf:
/remote/apps/depot/linux/Qt-4.3.3/lib/libQtGui.prl:
/remote/apps/depot/linux/Qt-4.3.3/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile NuMeth.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/NuMeth1.0.0 || $(MKDIR) .tmp/NuMeth1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NuMeth1.0.0/ && $(COPY_FILE) --parents cmp.h derivation.h divideddiffs.h divnode.h function.h functionparser.h integration.h interpolation.h mainwindow.h numethwizard.h plotter.h .tmp/NuMeth1.0.0/ && $(COPY_FILE) --parents numeth.qrc numethwizard.qrc plotter.qrc .tmp/NuMeth1.0.0/ && $(COPY_FILE) --parents derivation.cpp divideddiffs.cpp function.cpp functionparser.cpp integration.cpp interpolation.cpp main.cpp mainwindow.cpp numethwizard.cpp plotter.cpp .tmp/NuMeth1.0.0/ && (cd `dirname .tmp/NuMeth1.0.0` && $(TAR) NuMeth1.0.0.tar NuMeth1.0.0 && $(COMPRESS) NuMeth1.0.0.tar) && $(MOVE) `dirname .tmp/NuMeth1.0.0`/NuMeth1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NuMeth1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_numethwizard.cpp moc_plotter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_numethwizard.cpp moc_plotter.cpp
moc_mainwindow.cpp: mainwindow.h
	/remote/apps/depot/linux/Qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_numethwizard.cpp: numethwizard.h
	/remote/apps/depot/linux/Qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) numethwizard.h -o moc_numethwizard.cpp

moc_plotter.cpp: plotter.h
	/remote/apps/depot/linux/Qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) plotter.h -o moc_plotter.cpp

compiler_rcc_make_all: qrc_numeth.cpp qrc_numethwizard.cpp qrc_plotter.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_numeth.cpp qrc_numethwizard.cpp qrc_plotter.cpp
qrc_numeth.cpp: numeth.qrc \
		images/open.png \
		images/gauss.png \
		images/nm.png \
		images/funcCalc.png \
		images/lagrangeCalc.png \
		images/errorLag.png \
		images/linearConst.png \
		images/simpson.png \
		images/save.png \
		images/lagrange.png \
		images/divdiff.png \
		images/nm.jpg \
		images/seqConst.png \
		images/new.png \
		images/splash.jpg \
		images/tchebishev.png \
		images/newtonCalc.png \
		images/exit.png \
		images/rec.png \
		images/newton.png \
		images/trap.png
	/remote/apps/depot/linux/Qt-4.3.3/bin/rcc -name numeth numeth.qrc -o qrc_numeth.cpp

qrc_numethwizard.cpp: numethwizard.qrc \
		images/logo.png \
		images/watermark.jpg
	/remote/apps/depot/linux/Qt-4.3.3/bin/rcc -name numethwizard numethwizard.qrc -o qrc_numethwizard.cpp

qrc_plotter.cpp: plotter.qrc \
		images/zoomIn.png \
		images/zoomOut.png
	/remote/apps/depot/linux/Qt-4.3.3/bin/rcc -name plotter plotter.qrc -o qrc_plotter.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

derivation.o: derivation.cpp derivation.h \
		function.h \
		functionparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o derivation.o derivation.cpp

divideddiffs.o: divideddiffs.cpp divideddiffs.h \
		divnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o divideddiffs.o divideddiffs.cpp

function.o: function.cpp function.h \
		functionparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o function.o function.cpp

functionparser.o: functionparser.cpp functionparser.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functionparser.o functionparser.cpp

integration.o: integration.cpp integration.h \
		function.h \
		derivation.h \
		functionparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integration.o integration.cpp

interpolation.o: interpolation.cpp interpolation.h \
		function.h \
		cmp.h \
		functionparser.h \
		derivation.h \
		divideddiffs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interpolation.o interpolation.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		interpolation.h \
		function.h \
		integration.h \
		numethwizard.h \
		plotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

numethwizard.o: numethwizard.cpp numethwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numethwizard.o numethwizard.cpp

plotter.o: plotter.cpp plotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotter.o plotter.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_numethwizard.o: moc_numethwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numethwizard.o moc_numethwizard.cpp

moc_plotter.o: moc_plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotter.o moc_plotter.cpp

qrc_numeth.o: qrc_numeth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_numeth.o qrc_numeth.cpp

qrc_numethwizard.o: qrc_numethwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_numethwizard.o qrc_numethwizard.cpp

qrc_plotter.o: qrc_plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_plotter.o qrc_plotter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

